version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  sunbird_build_json:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: Build app

workflows:
    sunbird_resource_bundles:
    jobs:
      - sunbird_build_json